# Generated by Django 3.1.2 on 2020-10-27 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idea',
            options={'ordering': ['-id']},
        ),
    ]
