# Generated by Django 3.1.2 on 2020-11-15 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_idea_timestamo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idea',
            old_name='timestamo',
            new_name='timestamp',
        ),
    ]
