# Generated by Django 3.1.2 on 2020-11-21 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0004_auto_20201119_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='titla',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
