# Generated by Django 3.1.2 on 2020-11-21 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0005_idea_titla'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idea',
            old_name='titla',
            new_name='title',
        ),
    ]
