# Generated by Django 3.1.2 on 2020-11-21 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0006_auto_20201121_0403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='title',
        ),
    ]
