# Generated by Django 3.1.2 on 2020-11-22 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0007_remove_idea_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='title',
            field=models.CharField(default='Idea Title', max_length=100),
            preserve_default=False,
        ),
    ]
