# Generated by Django 3.1.2 on 2020-11-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0008_idea_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idea',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RenameField(
            model_name='idea',
            old_name='content',
            new_name='problem',
        ),
        migrations.AddField(
            model_name='idea',
            name='current_solution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='idea',
            name='ideal_solution',
            field=models.TextField(blank=True, null=True),
        ),
    ]
