# Generated by Django 3.1.2 on 2020-11-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0013_auto_20201125_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='image',
            field=models.ImageField(default='default_article.jpg', upload_to='article_img'),
        ),
    ]
