# Generated by Django 3.1.2 on 2020-11-26 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0016_auto_20201125_1357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idea',
            old_name='image',
            new_name='demo_picture',
        ),
    ]
