# Generated by Django 3.1.2 on 2020-12-02 00:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0019_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='problem',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
