# Generated by Django 3.1.2 on 2020-12-02 15:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0020_auto_20201202_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='idea',
            name='current_solution',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='idea',
            name='ideal_solution',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
